#!/bin/bash

if(($# == 1)); then
    filename=$1
    len=${#filename}
    last=${filename:len-2}
    rightlast=.s
    if [ "$last" = "$rightlast" ]; then 
        finalfile=${filename:0:len-2}
        if test -f $finalfile; then
            rm $finalfile
        fi
        if test -f $finalfile.o; then 
            rm $finalfile.o
        fi
        as $finalfile.s -o $finalfile.o
        if test -f $finalfile.o; then
            ld $finalfile.o -o $finalfile
            rm $finalfile.o
        fi
    else
        echo Please check your input file
    fi
else
    echo asc [file.s]
fi