#!/bin/bash

if (($#!=1))
then
    echo "ccs [c script].ccs";
    exit 1;
fi

file=$1;

if ((${#file} <= 4))
then
    echo "ccs [c script].ccs";
    exit 1;
fi

if [[ "${file:${#file}-4:${#file}}" != ".ccs" ]]
then
    echo "ccs [c script].ccs";
    exit 1;
fi

if ! `test -d ".cs_vir_dir"`
then
	mkdir .cs_vir_dir;
fi

cat > .cs_vir_dir/"${file}_tmp.c" << EOF
#include <jlib.h>
int main(void){
EOF

cat "${file}" >> .cs_vir_dir/"${file}_tmp.c";

cat >> .cs_vir_dir/"${file}_tmp.c" << EOF
return 0;}
EOF

clang .cs_vir_dir/"${file}_tmp.c" -o .cs_vir_dir/"${file}_tmp" && ./.cs_vir_dir/"${file}_tmp";

rm -fr .cs_vir_dir;
