#!/bin/bash

if(($# == 1)); then
    filename=$1
    len=${#filename}
    last=${filename:len-2}
    rightlast=.s
    if [ "$last" = "$rightlast" ]; then 
        finalfile=${filename:0:len-2}
        if test -f $finalfile; then
            rm $finalfile
        fi
		if test -f $finalfile.o; then
			rm $finalfile.o;
		fi
		clang -c $filename -o $finalfile.o
        clang $finalfile.o -o $finalfile
		if test -f $finalfile.o; then
			rm $finalfile.o;
		fi
		if test -f $finalfile; then
			./$finalfile;
			rm $finalfile;
		fi
    else
        echo Please check your input file
    fi
else
    echo clangsr [file.s]
fi
