#!/bin/bash

if(($# == 1)); then
    filename=$1
    len=${#filename}
    last=${filename:len-2}
    rightlast=.c
    if [ "$last" = "$rightlast" ]; then 
        finalfile=${filename:0:len-2}
        if test -f /tmp/clgr/$finalfile; then
            rm /tmp/clgr/$finalfile
        fi
        clang $1 -o /tmp/clgr/$finalfile
        if test -f /tmp/clgr/$finalfile; then
            /tmp/clgr/./$finalfile
        fi
        if test -f /tmp/clgr/$finalfile; then
            rm /tmp/clgr/$finalfile
        fi
    else
        echo Please check your input file
    fi
else
    echo clgr [file.c]
fi
