#!/bin/bash

if (($# == 1))
then
    filename=$1
    len=${#filename}
    last=${filename:len-4}
    rightlast=.asm
    if [ "$last" = "$rightlast" ]; then 
        filename=${filename:0:len-4}
        finalfile=$filename
        finalfile+='.o'
        if test -f $finalfile; then
            rm $finalfile
        fi
        nasm -f elf $1
        if test -f $filename; then
            rm $filename
        fi
        ld -m elf_i386 -s -o $filename $finalfile
        rm $finalfile
    else
        echo Please check your input file
    fi
else
    echo nasmc [file.asm]
fi